/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelAddEditRemove.java
 *
 * Created on 21.04.2009, 18:34:32
 */

package view;

import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import util.PropsUtil;

/**
 *
 * @author е
 */
public class JPanelAddEditRemove extends javax.swing.JPanel {

    /** Creates new form JPanelAddEditRemove */
    public JPanelAddEditRemove() {
        initComponents();
        loadTextProps();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAdd = new javax.swing.JButton();
        jButtonRemove = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();

        jButtonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/resources/icons/notebook__plus.png"))); // NOI18N

        jButtonRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/resources/icons/notebook__minus.png"))); // NOI18N

        jButtonEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/resources/icons/notebook__pencil.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButtonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonRemove;
    // End of variables declaration//GEN-END:variables

    public void addjButtonAddActionListener(ActionListener l)
    {
        jButtonAdd.addActionListener(l);
    }
    public void removejButtonNextActionListener(ActionListener l)
    {
        jButtonAdd.removeActionListener(l);
    }

    public void addjButtonEditActionListener(ActionListener l)
    {
        jButtonEdit.addActionListener(l);
    }
    public void removejButtonEditActionListener(ActionListener l)
    {
        jButtonEdit.removeActionListener(l);
    }

    public void addjButtonRemoveActionListener(ActionListener l)
    {
        jButtonRemove.addActionListener(l);
    }
    public void removejButtonRemoveActionListener(ActionListener l)
    {
        jButtonRemove.removeActionListener(l);
    }

    private void loadTextProps() {
//        jButtonAdd.setIcon(new ImageIcon(
//                getClass().getResource(PropsUtil.getProperty("icon.add"))));
//        jButtonEdit.setIcon(new ImageIcon(
//                getClass().getResource(PropsUtil.getProperty("icon.edit"))));
//        jButtonRemove.setIcon(new ImageIcon(
//                getClass().getResource(PropsUtil.getProperty("icon.remove"))));
        jButtonAdd.setToolTipText(PropsUtil.getProperty("add.text"));
        jButtonEdit.setToolTipText(PropsUtil.getProperty("edit.text"));
        jButtonRemove.setToolTipText(PropsUtil.getProperty("remove.text"));
        jButtonAdd.setText("");
        jButtonEdit.setText("");
        jButtonRemove.setText("");
    }
}
