/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelSupplyList.java
 *
 * Created on 26.02.2009, 17:50:46
 */

package view;

import entity.Supply;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.JScrollBar;
import javax.swing.JTable;
import javax.swing.table.TableCellRenderer;
import view.componentmodels.TMSupply;

/**
 *
 * @author е
 */
public class JPanelSupplyList extends javax.swing.JPanel {

    private List<Supply> ListPrices;

    /** Creates new form JPanelSupplyList */
    public JPanelSupplyList() {
        initComponents();
        getTable().setColumnSelectionAllowed(false);
    }

    public JPanelSupplyList(List<Supply> list) {
        this();
        setItemList(list);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPanePriceList = new javax.swing.JScrollPane();
        jTablePriceList = new javax.swing.JTable();
        jPanelSearch1 = new view.JPanelSearch();

        jTablePriceList.setFont(new java.awt.Font("Arial", 0, 12));
        jTablePriceList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "№", "Наименование", "Артикул", "Цена", "Остаток"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePriceList.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTablePriceList.setColumnSelectionAllowed(true);
        jTablePriceList.getTableHeader().setReorderingAllowed(false);
        jScrollPanePriceList.setViewportView(jTablePriceList);
        jTablePriceList.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPanePriceList, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPanePriceList, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.JPanelSearch jPanelSearch1;
    private javax.swing.JScrollPane jScrollPanePriceList;
    private javax.swing.JTable jTablePriceList;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jPanelSearch
     */
    public view.JPanelSearch getJPanelSearch() {
        return jPanelSearch1;
    }

    /**
     * @return the jTablePriceList
     */
    public javax.swing.JTable getTable() {
        return jTablePriceList;
    }

    /**
     * @return the jScrollPanePriceList
     */
    public javax.swing.JScrollPane getScrollPane() {
        return jScrollPanePriceList;
    }

    public void setColumnVisible(int index, boolean isVisible){
        int tmp = 0;
        try {
            if (isVisible)
                tmp = ((TMSupply)getTable().getModel()).getColumnPreferredWidth(index);
        }
        catch (ClassCastException ex) {
            System.out.println(ex.getMessage());
        }
        getTable().getColumnModel().getColumn(index).setPreferredWidth(tmp);
    }

        /**
     * @return the ListPrices
     */
    public List<Supply> getItemList() {
        return ListPrices;
    }

    public void setItemList(List<Supply> list) {
        ListPrices = list;
        getTable().setModel(new TMSupply(ListPrices));
        for(int i = 0; i < getTable().getColumnCount(); i++)
            getTable().getColumnModel().getColumn(i).setMinWidth(0);
        setSelectedIndex(0);

        //setCellAppearance();
        }

    /**
     * Устанавливает способ представления значений ячеек таблицы (визуальное отображение)
     */
    protected void setCellAppearance() {
        Component c;
        Color color;
        for(int i = 0; i < getTable().getRowCount(); i++) {
            if (ListPrices.get(i).getAmountLeft() <= ListPrices.get(i).getAmountMin())
                color = Color.RED;
            else color = Color.GREEN;
            
            //СПРОСИТЬ ВАДИКА!
            c = getTable().getCellRenderer(i, 5).getTableCellRendererComponent(jTablePriceList, ListPrices.get(i), false, false, i, 5);
            c.setForeground(color);
            //.setCellRenderer(getTable().getCellRenderer(i, 5));
        }
    }

    public Supply getSelectedItem(){
        try {
            return ListPrices.get(getTable().getSelectedRow());
        }
        catch (IndexOutOfBoundsException ex) {
            return null;
        }
        catch (IllegalStateException ex){
            return null;
        }
    }

    public void setSelectedItem(Supply p){
        setSelectedIndex(ListPrices.indexOf(p));
    }

    public int getSelectedIndex(){
        return getTable().getSelectedRow();
    }

    public void setSelectedIndex(int index){
        if (index < 0 || index >= getTable().getRowCount()) return;
        getTable().setRowSelectionInterval(index, index);

        JScrollBar Scroll = getScrollPane().getVerticalScrollBar();
        int tmp = (Scroll.getMaximum() - Scroll.getMinimum())
                *(ListPrices.size() - index)/ListPrices.size();
        Scroll.setValue(Scroll.getMaximum() - tmp);        
    }
}

//class MyTableCellRenderer extends javax.​swing.​table.DefaultTableCellRender implements TableCellRenderer {
//
//    public MyTableCellRenderer() {
//        super();
//    }
//}
