/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelRequest.java
 *
 * Created on 31.05.2009, 20:55:06
 */

package view.panel;

import entity.Request;

/**
 *
 * @author е
 */
public class JPanelRequest extends javax.swing.JPanel implements IEntityView<Request>{

    /** Creates new form JPanelRequest */
    public JPanelRequest() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public boolean isEditable() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void setEditable(boolean Editable) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public Request getData() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void setData(Request data) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void clearData() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void updateDisplay() {
        throw new UnsupportedOperationException("Not supported yet.");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
