/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormPriceList.java
 *
 * Created on 17.02.2009, 23:33:00
 */

package view;

import java.awt.event.ActionEvent;
import entity.Price;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.JOptionPane;
import util.PropsUtil;
import view.JPanelPriceList;

/**
 *
 * @author е
 */
public class FormPriceList extends javax.swing.JFrame {

    /** Creates new form FormPriceList */
    public FormPriceList(List<Price> list) {
        initComponents();
        jPanelPriceList.setListPrices(list);
        try {
            this.setIconImage(ImageIO.read(new File("src/view/icons/hammer_screwdriver.png")));
        } catch (IOException ex) {
            Logger.getLogger(FormPriceList.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JCheckBoxMenuItem m = null;
        ActionListener l = new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                setVisiblePriceColumns();
            }
        };
        for(int i = 0; i < jPanelPriceList.getTable().getColumnCount(); i++){
            m = new JCheckBoxMenuItem(jPanelPriceList.getTable().getColumnName(i), true);
            m.addActionListener(l);
            jMenuView.add(m);
        }
        setVisiblePriceColumns();
        loadTextProps();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPriceList = new view.JPanelPriceList();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemSaveAs = new javax.swing.JMenuItem();
        jMenuItemQuit = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuItemAdd = new javax.swing.JMenuItem();
        jMenuItemEdit = new javax.swing.JMenuItem();
        jMenuItemDelete = new javax.swing.JMenuItem();
        jMenuView = new javax.swing.JMenu();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Trader Tools");

        jMenuFile.setText("Файл");

        jMenuItemSaveAs.setText("Сохранить как...");
        jMenuFile.add(jMenuItemSaveAs);

        jMenuItemQuit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemQuit.setText("Выход");
        jMenuItemQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQuitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemQuit);

        jMenuBar1.add(jMenuFile);

        jMenuEdit.setText("Правка");

        jMenuItemAdd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_EQUALS, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/notebook__plus.png"))); // NOI18N
        jMenuItemAdd.setText("Add");
        jMenuEdit.add(jMenuItemAdd);

        jMenuItemEdit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/notebook__pencil.png"))); // NOI18N
        jMenuItemEdit.setText("Edit");
        jMenuEdit.add(jMenuItemEdit);

        jMenuItemDelete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        jMenuItemDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/notebook__minus.png"))); // NOI18N
        jMenuItemDelete.setText("Delete");
        jMenuEdit.add(jMenuItemDelete);

        jMenuBar1.add(jMenuEdit);

        jMenuView.setText("View");
        jMenuBar1.add(jMenuView);

        jMenuHelp.setText("Help");

        jMenuItemAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/information_frame.png"))); // NOI18N
        jMenuItemAbout.setText("About");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemAbout);

        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPriceList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPriceList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQuitActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItemQuitActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
        JOptionPane.showMessageDialog(this, PropsUtil.getProperty("FormPriceList.About.text"), 
                PropsUtil.getProperty("jMenuItemAbout.text"), JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItemAboutActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemAdd;
    private javax.swing.JMenuItem jMenuItemDelete;
    private javax.swing.JMenuItem jMenuItemEdit;
    private javax.swing.JMenuItem jMenuItemQuit;
    private javax.swing.JMenuItem jMenuItemSaveAs;
    private javax.swing.JMenu jMenuView;
    private view.JPanelPriceList jPanelPriceList;
    // End of variables declaration//GEN-END:variables


    public void addjMenuItemAddActionListener(ActionListener l)
    {
        jMenuItemAdd.addActionListener(l);
    }
    public void removejMenuItemAddActionListener(ActionListener l)
    {
        jMenuItemAdd.removeActionListener(l);
    }

    public void addjMenuItemEditActionListener(final ActionListener l)
    {
        MouseListener buf = new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
               if (e.getClickCount() == 2)
                   l.actionPerformed(null);
            }
        };
        getJPanelPriceList().getTable().addMouseListener(buf);
        jMenuItemEdit.addActionListener(l);
    }
    public void removejMenuItemEditActionListener(ActionListener l)
    {
        jMenuItemEdit.removeActionListener(l);
    }

    public void addjMenuItemDeleteActionListener(ActionListener l)
    {
        jMenuItemDelete.addActionListener(l);
    }
    public void removejMenuItemDeleteActionListener(ActionListener l)
    {
        jMenuItemDelete.removeActionListener(l);
    }

    /**
     * @return the jPanelPriceList.getJPanelSearch()
     */
    public view.JPanelSearch getJPanelSearch() {
        return jPanelPriceList.getJPanelSearch();
    }

    public view.JPanelPriceList getJPanelPriceList() {
        return jPanelPriceList;
    }

    public Price getSelectedPrice(){
        return jPanelPriceList.getSelectedPrice();
    }

    public int getSelectedPriceIndex(){
        return jPanelPriceList.getSelectedPriceIndex();
    }

    public void setSelectedPrice(Price p){
        jPanelPriceList.setSelectedPrice(p);
    }

    public void setSelectedPrice(int index){
        jPanelPriceList.setSelectedPrice(index);
    }

    public void setVisiblePriceColumns(){
        for(int i = 0; i < jPanelPriceList.getTable().getColumnCount(); i++){
            jPanelPriceList.setColumnVisible(i,((JCheckBoxMenuItem)jMenuView.getItem(i)).getState());
        }
    }

    private void loadTextProps() {
        setTitle(PropsUtil.getProperty("FormPriceList.title"));
        jMenuFile.setText(PropsUtil.getProperty("jMenuFile.text"));
        jMenuItemSaveAs.setText(PropsUtil.getProperty("jMenuItemSaveAs.text"));
        jMenuItemQuit.setText(PropsUtil.getProperty("jMenuItemQuit.text"));
        jMenuEdit.setText(PropsUtil.getProperty("jMenuEdit.text"));
        jMenuView.setText(PropsUtil.getProperty("jMenuView.text"));
        jMenuHelp.setText(PropsUtil.getProperty("jMenuHelp.text"));
        jMenuItemAbout.setText(PropsUtil.getProperty("jMenuItemAbout.text"));
    }
}
