/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormCustomerManager.java
 *
 * Created on 01.03.2009, 23:35:12
 */

package view;

import dao.DaoFactory;
import entity.Bill;
import entity.Customer;
import entity.Invoice;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Collection;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import util.PropsUtil;
import view.componentmodels.GenericListModel;

/**
 *
 * @author е
 */
public class FormCustomerManager extends javax.swing.JFrame {

    Customer MySelf;
    /** Creates new form FormCustomerManager */
    public FormCustomerManager(Customer myself, List<Customer> list, final boolean showSuppliers) {//true - show Suppliers, false - show Clients
        initComponents();
        loadTextProps();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        MySelf = myself;
        for(int i = 0; i < list.size(); i++) {
            Customer c = list.get(i);
            if (!c.getIsSupplier() == showSuppliers) {
                list.remove(c);
                i--;
            }
        }        
        jListCustomers.setModel(new GenericListModel(list));
        
        ListSelectionListener sl = new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent e) {
                Customer buf = (Customer) jListCustomers.getSelectedValue();
                jPanelCustomerFullInfo1.setData(buf);
                BigDecimal Balance = new BigDecimal(0.00);
                List<Invoice> invoices = null;
                List<Bill> bills = null;
                if (showSuppliers) {
                    invoices = DaoFactory.getInvoiceDao().getList(buf, MySelf); //мы получили от поставщика
                    bills = DaoFactory.getBillDao().getList(buf, MySelf);//мы заплатили поставщикам                    
                } else {
                    invoices = DaoFactory.getInvoiceDao().getList(MySelf, buf); //мы продали клиентам
                    bills = DaoFactory.getBillDao().getList(MySelf, buf); //мы получили оплату от клиентов
                }
                jListInvoices.setModel(new GenericListModel(invoices));
                jListBills.setModel(new GenericListModel(bills));
                for(Invoice o : invoices) {
                    Balance = Balance.subtract(o.getInvoiceSum());
                }
                for(Bill o : bills) {
                    Balance = Balance.add(o.getBillSum());
                }
                jLabelBalance.setText("Итоговый баланс: " + Balance.toString());
                if (Balance.longValue() < 0) 
                    jLabelBalance.setForeground(Color.RED);
                else jLabelBalance.setForeground(Color.BLACK);
                //if (!showSuppliers) Balance.multiply(new BigDecimal(-1));
            }
        };
        jListCustomers.addListSelectionListener(sl);

        if (!list.isEmpty()) jListCustomers.setSelectedIndex(0);        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCustomerFullInfo1 = new view.JPanelCustomerFullInfo();
        jPanelAddEditRemove1 = new view.JPanelAddEditRemove();
        jPanelSearch1 = new view.JPanelSearch();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListCustomers = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListBills = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListInvoices = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListRequests = new javax.swing.JList();
        jLabelBalance = new javax.swing.JLabel();
        jButtonNewInvoice = new javax.swing.JButton();
        jButtonNewBill = new javax.swing.JButton();
        jButtonNewRequest = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemNewInvoice = new javax.swing.JMenuItem();
        jMenuItemQuit = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuItemAdd = new javax.swing.JMenuItem();
        jMenuItemEdit = new javax.swing.JMenuItem();
        jMenuItemRemove = new javax.swing.JMenuItem();
        jMenuItemSupplyList = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelCustomerFullInfo1.setEnabled(false);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(5, 0));

        jListCustomers.setBorder(javax.swing.BorderFactory.createTitledBorder("Customers"));
        jListCustomers.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListCustomers);

        jListBills.setBorder(javax.swing.BorderFactory.createTitledBorder("Платежи"));
        jListBills.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListBills);

        jListInvoices.setBorder(javax.swing.BorderFactory.createTitledBorder("Счета"));
        jListInvoices.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jListInvoices);

        jListRequests.setBorder(javax.swing.BorderFactory.createTitledBorder("Заказы"));
        jScrollPane4.setViewportView(jListRequests);

        jLabelBalance.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelBalance.setText("Итоговый баланс:");

        jButtonNewInvoice.setText("Новый счет");

        jButtonNewBill.setText("Новый платеж");

        jButtonNewRequest.setText("Новый заказ");

        jMenuFile.setText("File");

        jMenuItemNewInvoice.setText("New invoice");
        jMenuFile.add(jMenuItemNewInvoice);

        jMenuItemQuit.setText("Quit");
        jMenuItemQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQuitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemQuit);

        jMenuBar1.add(jMenuFile);

        jMenuEdit.setText("Edit");

        jMenuItemAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/resources/icons/notebook__plus.png"))); // NOI18N
        jMenuItemAdd.setText("Add");
        jMenuEdit.add(jMenuItemAdd);

        jMenuItemEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/resources/icons/notebook__pencil.png"))); // NOI18N
        jMenuItemEdit.setText("Edit");
        jMenuEdit.add(jMenuItemEdit);

        jMenuItemRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/resources/icons/notebook__minus.png"))); // NOI18N
        jMenuItemRemove.setText("Remove");
        jMenuItemRemove.setEnabled(false);
        jMenuEdit.add(jMenuItemRemove);

        jMenuItemSupplyList.setText("Supply List");
        jMenuEdit.add(jMenuItemSupplyList);

        jMenuItem1.setText("PriceList Manager?");
        jMenuEdit.add(jMenuItem1);

        jMenuBar1.add(jMenuEdit);

        jMenuHelp.setText("help");

        jMenuItemAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/resources/icons/information_frame.png"))); // NOI18N
        jMenuItemAbout.setText("About");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemAbout);

        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelAddEditRemove1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelBalance)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonNewInvoice)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonNewBill))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonNewRequest)
                                        .addGap(61, 61, 61))
                                    .addComponent(jScrollPane4, 0, 0, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addComponent(jPanelCustomerFullInfo1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelAddEditRemove1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                        .addGap(11, 11, 11)
                        .addComponent(jPanelSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanelCustomerFullInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonNewInvoice)
                            .addComponent(jButtonNewBill)
                            .addComponent(jButtonNewRequest))
                        .addGap(17, 17, 17)
                        .addComponent(jLabelBalance)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQuitActionPerformed
         this.dispose();
    }//GEN-LAST:event_jMenuItemQuitActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
          JOptionPane.showMessageDialog(this, PropsUtil.getProperty("FormCustomerManager.About.text"),
                PropsUtil.getProperty("jMenuItemAbout.text"), JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNewBill;
    private javax.swing.JButton jButtonNewInvoice;
    private javax.swing.JButton jButtonNewRequest;
    private javax.swing.JLabel jLabelBalance;
    private javax.swing.JList jListBills;
    private javax.swing.JList jListCustomers;
    private javax.swing.JList jListInvoices;
    private javax.swing.JList jListRequests;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemAdd;
    private javax.swing.JMenuItem jMenuItemEdit;
    private javax.swing.JMenuItem jMenuItemNewInvoice;
    private javax.swing.JMenuItem jMenuItemQuit;
    private javax.swing.JMenuItem jMenuItemRemove;
    private javax.swing.JMenuItem jMenuItemSupplyList;
    private view.JPanelAddEditRemove jPanelAddEditRemove1;
    private view.JPanelCustomerFullInfo jPanelCustomerFullInfo1;
    private view.JPanelSearch jPanelSearch1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    private void loadTextProps() {
        setTitle(PropsUtil.getProperty("FormCustomerManager.title"));
        jMenuFile.setText(PropsUtil.getProperty("jMenuFile.text"));
        //jMenuItemSaveAs.setText(PropsUtil.getProperty("jMenuItemSaveAs.text"));
        jMenuItemQuit.setText(PropsUtil.getProperty("jMenuItemQuit.text"));
        jMenuEdit.setText(PropsUtil.getProperty("jMenuEdit.text"));
        //jMenuView.setText(PropsUtil.getProperty("jMenuView.text"));
        jMenuHelp.setText(PropsUtil.getProperty("jMenuHelp.text"));
        jMenuItemAbout.setText(PropsUtil.getProperty("jMenuItemAbout.text"));
        try {
            this.setIconImage(ImageIO.read(new File(PropsUtil.getProperty("icon.hammer"))));
        } catch (IOException ex) {
            Logger.getLogger(FormSupplyList.class.getName()).log(Level.SEVERE, null, ex);
        }
        jMenuItemAdd.setIcon(new ImageIcon(
                getClass().getResource(PropsUtil.getProperty("icon.add"))));
        jMenuItemEdit.setIcon(new ImageIcon(
                getClass().getResource(PropsUtil.getProperty("icon.edit"))));
        jMenuItemRemove.setIcon(new ImageIcon(
                getClass().getResource(PropsUtil.getProperty("icon.remove"))));
        jMenuItemAbout.setIcon(new ImageIcon(
                getClass().getResource(PropsUtil.getProperty("icon.info"))));
    }
}
