/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelSearch.java
 *
 * Created on 18.02.2009, 0:51:19
 */

package view;

import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.event.DocumentListener;
import util.PropsUtil;

/**
 *
 * @author е
 */
public class JPanelSearch extends javax.swing.JPanel {

    private boolean havingResult;
    /** Creates new form JPanelSearch */
    public JPanelSearch() {
        initComponents();
        loadTextProps();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFind = new javax.swing.JLabel();
        jTextFieldSearchTemplate = new javax.swing.JTextField();
        jButtonNext = new javax.swing.JButton();
        jButtonPrev = new javax.swing.JButton();

        jLabelFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/resources/icons/binocular.png"))); // NOI18N
        jLabelFind.setText("Найти:");

        jTextFieldSearchTemplate.setPreferredSize(new java.awt.Dimension(100, 20));

        jButtonNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/resources/icons/arrow_270.png"))); // NOI18N
        jButtonNext.setText("Next");
        jButtonNext.setMaximumSize(new java.awt.Dimension(73, 23));
        jButtonNext.setMinimumSize(new java.awt.Dimension(73, 23));
        jButtonNext.setPreferredSize(new java.awt.Dimension(90, 23));

        jButtonPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/resources/icons/arrow_090.png"))); // NOI18N
        jButtonPrev.setText("Prev.");
        jButtonPrev.setPreferredSize(new java.awt.Dimension(90, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelFind)
                .addGap(3, 3, 3)
                .addComponent(jTextFieldSearchTemplate, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNext, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPrev, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                .addComponent(jLabelFind)
                .addComponent(jButtonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextFieldSearchTemplate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrev;
    private javax.swing.JLabel jLabelFind;
    private javax.swing.JTextField jTextFieldSearchTemplate;
    // End of variables declaration//GEN-END:variables

    public void addjButtonNextActionListener(ActionListener l)
    {
        jButtonNext.addActionListener(l);
    }
    public void removejButtonNextActionListener(ActionListener l)
    {
        jButtonNext.removeActionListener(l);
    }

    public void addjButtonPrevActionListener(ActionListener l)
    {
        jButtonPrev.addActionListener(l);
    }
    public void removejButtonPrevActionListener(ActionListener l)
    {
        jButtonPrev.removeActionListener(l);
    }

    public void addjTextFieldSearchTemplateDocumentListener(DocumentListener l)
    {
        jTextFieldSearchTemplate.getDocument().addDocumentListener(l);
    }
    public void removejTextFieldSearchTemplateDocumentListener(DocumentListener l)
    {
        jTextFieldSearchTemplate.getDocument().removeDocumentListener(l);
    }

    /**
     * @return the havingResult
     */
    public boolean isHavingResult() {
        return havingResult;
    }

    /**
     * @param havingResult the havingResult to set
     */
    public void setHavingResult(boolean havingResult) {
        this.havingResult = havingResult;
        Color bg = havingResult ? Color.GREEN : Color.RED;
        jTextFieldSearchTemplate.setBackground(bg);
    }

    public String getSearchTemplate(){
        return jTextFieldSearchTemplate.getText();
    }

    public void setSearchTemplate(String template){
        jTextFieldSearchTemplate.setText(template);
    }

    private void loadTextProps() {
        jLabelFind.setText(PropsUtil.getProperty("JPanelSearch.jLabelFind.text"));
        jButtonNext.setText(PropsUtil.getProperty("JPanelSearch.jButtonNext.text"));
        jButtonPrev.setText(PropsUtil.getProperty("JPanelSearch.jButtonPrev.text"));
//        jLabelFind.setIcon(new ImageIcon(
//                getClass().getResource(PropsUtil.getProperty("icon.find"))));
//        jButtonNext.setIcon(new ImageIcon(
//                getClass().getResource(PropsUtil.getProperty("icon.down"))));
//        jButtonPrev.setIcon(new ImageIcon(
//                getClass().getResource(PropsUtil.getProperty("icon.up"))));

    }
}
