/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormBillCreator.java
 *
 * Created on 27.05.2009, 14:06:08
 */

package view.form;

import view.*;
import controller.CustomerManagingTool;
import entity.Bill;
import entity.Customer;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.List;
import view.componentmodel.GenericListModel;
import view.panel.JPanelBill;

/**
 *
 * @author е
 */
public class FormBillCreator extends javax.swing.JFrame
        implements IFormCreator<Bill> {

    private Customer Myself;
    private final int mode;//TODO: mode - send and receive

    /** Creates new form FormBillCreator */
    public FormBillCreator(Customer myself, List<Customer> list, final int mode) {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setTitle("New Bill");
        jPanelBill1.setEditable(true);
        this.Myself = myself;
        this.mode = mode;

        if (mode == CustomerManagingTool.MODE_RECEIVE)
                    jPanelBill1.getData().setReceiverId(Myself);
                if (mode == CustomerManagingTool.MODE_SEND)
                    jPanelBill1.getData().setSenderId(Myself);
        jPanelBill1.updateDisplay();
        jComboBoxCustomer.setModel(new GenericListModel(list));
        
        ItemListener il = new ItemListener() {

            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED)
                if (mode == CustomerManagingTool.MODE_SEND)
                    jPanelBill1.getData().setReceiverId((Customer)e.getItem());
                if (mode == CustomerManagingTool.MODE_RECEIVE)
                    jPanelBill1.getData().setSenderId((Customer)e.getItem());
                jPanelBill1.updateDisplay();
            }
        };
        jComboBoxCustomer.addItemListener(il); //выбор customer, зависит от mode
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelOkCancel1 = new view.JPanelOkCancel();
        jComboBoxCustomer = new javax.swing.JComboBox();
        jPanelBill1 = new view.panel.JPanelBill();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBoxCustomer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCustomer.setBorder(javax.swing.BorderFactory.createTitledBorder("Client"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxCustomer, 0, 255, Short.MAX_VALUE)
                    .addComponent(jPanelOkCancel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelBill1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelBill1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelOkCancel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxCustomer;
    private view.panel.JPanelBill jPanelBill1;
    private view.JPanelOkCancel jPanelOkCancel1;
    // End of variables declaration//GEN-END:variables


    public Bill getData() {
        return jPanelBill1.getData();
    }

    public JPanelOkCancel getJPanelOkCancel() {
        return jPanelOkCancel1;
    }

    public JPanelBill getPanel() {
        return jPanelBill1;
    }

    public Customer getSelectedCustomer() {
        return (Customer) jComboBoxCustomer.getSelectedItem();
    }

    public void setSelectedCustomer(Customer c) {
        jComboBoxCustomer.setSelectedItem(c);
    }
}
