/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormInvoiceCreator.java
 *
 * Created on 01.03.2009, 23:21:47
 */

package view.form;

import view.*;
import controller.CustomerManagingTool;
import entity.Customer;
import entity.Invoice;
import entity.InvoiceProduct;
import entity.Supply;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import view.componentmodel.GenericListModel;
import view.panel.JPanelInvoice;

/**
 *
 * @author е
 * после выбора customer и начала работы с накладной запретить смену customer
 */
public class FormInvoiceCreator extends javax.swing.JFrame
        implements IFormCreator<Invoice> {

//    Customer SelectedItem;

    private Customer Myself;
    private final int mode;//TODO: mode - invoice and request
    /** Creates new form FormInvoiceCreator */
    public FormInvoiceCreator(Customer myself, List<Customer> list, int mode) {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setTitle("Новый счет");
        this.Myself = myself;
        this.mode = mode;
        jPanelSupplyList1.setEditable(false);
        jPanelInvoice1.setEditable(true);
        jPanelCustomerShortInfo1.setEditable(false);

        if (mode == CustomerManagingTool.MODE_CLIENTS) {
            jPanelSupplyList1.setItemList(Myself);
            jPanelSupplyList1.viewAllColumns();
            jPanelSupplyList1.setColumnVisible(2, false);//?! зависит от tmsupply
            jPanelSupplyList1.setColumnVisible(3, false);
            jPanelSupplyList1.setColumnVisible(4, false);
            jPanelSupplyList1.setColumnVisible(7, false);
        }

        jComboBoxCustomer.setModel(new GenericListModel(list));       
        ItemListener il = new ItemListener() {

            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED)
                updateDisplay((Customer)e.getItem());
            }
        };
        jComboBoxCustomer.addItemListener(il);

        ActionListener l = new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                jPanelInvoice1.clearData();
                jComboBoxCustomer.setEnabled(true);
            }
        };
        jButtonClearInvoice.addActionListener(l);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSupplyList1 = new view.JPanelSupplyList();
        jPanelInvoice1 = new view.panel.JPanelInvoice();
        jButtonAddInvoiceProduct = new javax.swing.JButton();
        jButtonRemoveInvoiceProduct = new javax.swing.JButton();
        jButtonClearInvoice = new javax.swing.JButton();
        jComboBoxCustomer = new javax.swing.JComboBox();
        jPanelCustomerShortInfo1 = new view.panel.JPanelCustomerShortInfo();
        jPanelOkCancel1 = new view.JPanelOkCancel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonAddInvoiceProduct.setText("->");

        jButtonRemoveInvoiceProduct.setText("<-");

        jButtonClearInvoice.setText("<<-");

        jComboBoxCustomer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ИП Иванов", "ЗАО \"Зарница\"" }));
        jComboBoxCustomer.setBorder(javax.swing.BorderFactory.createTitledBorder("Клиент"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanelSupplyList1, 0, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonClearInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonRemoveInvoiceProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAddInvoiceProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelCustomerShortInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelOkCancel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelInvoice1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelCustomerShortInfo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanelInvoice1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelOkCancel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanelSupplyList1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jButtonAddInvoiceProduct)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRemoveInvoiceProduct)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonClearInvoice)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddInvoiceProduct;
    private javax.swing.JButton jButtonClearInvoice;
    private javax.swing.JButton jButtonRemoveInvoiceProduct;
    private javax.swing.JComboBox jComboBoxCustomer;
    private view.panel.JPanelCustomerShortInfo jPanelCustomerShortInfo1;
    private view.panel.JPanelInvoice jPanelInvoice1;
    private view.JPanelOkCancel jPanelOkCancel1;
    private view.JPanelSupplyList jPanelSupplyList1;
    // End of variables declaration//GEN-END:variables

        // <editor-fold defaultstate="collapsed" desc="ActionListeners">
    public void addjButtonAddInvoiceProductActionListener(ActionListener l)
    {
        jButtonAddInvoiceProduct.addActionListener(l);
    }
    public void removejButtonAddInvoiceProductActionListener(ActionListener l)
    {
        jButtonAddInvoiceProduct.removeActionListener(l);
    }

    public void addjButtonRemoveInvoiceProductActionListener(ActionListener l)
    {
        jButtonRemoveInvoiceProduct.addActionListener(l);
    }
    public void removejButtonRemoveInvoiceProductActionListener(ActionListener l)
    {
        jButtonRemoveInvoiceProduct.removeActionListener(l);
    }

    // </editor-fold>

    protected void updateDisplay(Customer c) {
//        Customer c = (Customer) jComboBoxCustomer.getSelectedItem();
        jPanelCustomerShortInfo1.setData(c);
       
        if (mode == CustomerManagingTool.MODE_SUPPLIERS) { //TODO: переключение прайс-листов
            jPanelInvoice1.clearData();
            jPanelSupplyList1.setItemList(c);        
            jPanelSupplyList1.viewAllColumns();
            jPanelSupplyList1.setColumnVisible(2, false);
            jPanelSupplyList1.setColumnVisible(3, false);
            jPanelSupplyList1.setColumnVisible(6, false);
            getData().setBuyerId(Myself);
            getData().setSellerId(c);
        }
        else {
            getData().setBuyerId(c);
            getData().setSellerId(Myself);
        }
        jPanelInvoice1.updateDisplay();
    }

    /**
     * @return the invoice
     * 
     */
    public Invoice getData() {
        return jPanelInvoice1.getData();
    }

    public JPanelOkCancel getJPanelOkCancel() {
        return jPanelOkCancel1;
    }

    public JPanelInvoice getPanel() {
        return jPanelInvoice1;
    }

    public JPanelSupplyList getJPanelSupplyList() {
        return jPanelSupplyList1;
    }

    public Supply getSelectedSupply() {
        return jPanelSupplyList1.getSelectedItem();
    }

    public InvoiceProduct getSelectedInvoiceProduct() {
        return jPanelInvoice1.getSelectedItem();
    }

    public Customer getSelectedCustomer() {
        return (Customer) jComboBoxCustomer.getSelectedItem();
    }

    public void setSelectedCustomer(Customer c) {
        jComboBoxCustomer.setSelectedItem(c);
    }

    public boolean checkSelectedCustomer() {
        if (getSelectedCustomer() == null) {
            JOptionPane.showMessageDialog(this, "Выберите customer'а");
            return false;
        }
        return true;
    }
}
